### ISSUE TITLE
You cannot launch two optitrack_udp_client.launch instances at the same time

### ISSUE THREAD

**Issue by edcafenet** [IE-Robotics-Lab/optitrack_ros_communication#4]
You cannot launch two optitrack_udp_client.launch instances at the same time. The name of the node udp_generate_nodes never changes and therefore when you launch two instances it crashes. 

Can you add a time or PID number to the name of the node so multiple instances can be launched in parallel?

**Comment by paches00** [comment]
Commit c926e0d only solves node name conflict for pose data. A solution for "generate_udp_nodes" is still being explored.

**Comment by paches00** [comment]
optitrack_udp_client.launch can be run multiple times now
